### ISSUE TITLE
Too big right margin in `:Buffers` list for buffers with large number >999

### ISSUE THREAD

**Issue by gi4c0** [junegunn/fzf.vim#1237]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Just a little bug here. After opening a big amount of files if I go to `:Buffers` for those buffers that have number bigger then 999 the right margin gets too big:
![bug](https://user-images.githubusercontent.com/16100959/106489858-e1833100-64bd-11eb-8809-fde0ab8c666a.jpg)

**Comment by junegunn** [comment]
Thanks, it should be fixed now (unless you don't open more than 9999 buffers 😲)

**Comment by gi4c0** [comment]
Hey @junegunn, it seems like this bug returned.

**Comment by junegunn** [comment]
It looks fine to me.

```sh
vim {1..1000}
```

**Comment by gi4c0** [comment]
Weird but with `vim {1..1000}` everything is fine and when I work I'm still getting it:
![bug](https://user-images.githubusercontent.com/16100959/112339997-d207b380-8cc8-11eb-930b-205168d4cd8f.png)

**Comment by junegunn** [comment]
I see. It should be fixed now.
